mini_blog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
]

myapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home),
    path('about/',views.about,name="about"),
    path('dashboard/',views.dashboard,name="dashboard"),
    path('logout/',views.user_logout,name="logout"),
    path('signup/',views.user_signup,name="signup"),
    path('login/',views.user_login,name="login"),
    path('addblog/',views.add_blog,name='addblog'),
    path('updateblog/<int:id>/',views.update_blog,name="updateblog"),
    path('deleteblog/<int:id>/',views.delete_blog,name="deleteblog"),
]

myapp/models.py
from django.db import models

# Create your models here.
class BlogModel(models.Model):
    
    title = models.CharField(max_length=50)
    content = models.TextField()
    publication_date = models.DateField(auto_now_add=True)

     

myapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField
from django.contrib.auth.models import User
from .models import BlogModel

class SignupForm(UserCreationForm):
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput(attrs={'class':'form-control'}))
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
        # This if for formatting the Form.
        widgets  = {
            'username':forms.TextInput(attrs={'class':'form-control'}),
            'first_name':forms.TextInput(attrs={'class':'form-control'}),
            'last_name':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.EmailInput(attrs={'class':'form-control'}),
                    
                    }
        
class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={'autofocus':True, 'class':'form-control'}))
    password = forms.CharField(label=("password"),strip=False,widget=forms.PasswordInput(attrs={'autocomplete':'current-password', 'class':'form-control'}))

class BlogForm(forms.ModelForm):
    class Meta:
        model = BlogModel
        fields = ['title', 'content' ]
        widgets = {
            'title':forms.TextInput(attrs={'class':'form-control'}),
            'content':forms.Textarea(attrs={'class':'form-control'}),
            
            }
    

myapp/views.py
from django.shortcuts import render,HttpResponseRedirect
from .forms import SignupForm, LoginForm, BlogForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .models import BlogModel
from django.contrib.auth.models import Group


# Create your views here.

#Home
def home(request):
    blog = BlogModel.objects.all()
    return render(request, 'home.html',{'blog':blog})


#About
def about(request):
    return render(request,'about.html')


#Dashboard
def dashboard(request):
    blog=BlogModel.objects.all()
    if request.user.is_authenticated:
        return render(request,'dashboard.html',{'blog':blog})
    else:
        return HttpResponseRedirect('/login/')

#User logout
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')

#Signup
def user_signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user= form.save()
            group= Group.objects.get(name='Author')
            user.group.add(group)
    else:
        form = SignupForm()
    return render(request,'signup.html',{'form':form})

#Login
def user_login(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = LoginForm(request=request, data=request.POST)
            if form.is_valid():
                uname = form.cleaned_data['username']
                upass = form.cleaned_data['password']
                user = authenticate(username=uname, password=upass)
                if user is not None:
                    login(request,user)
                    messages.success(request, 'Logged in successfully')
                    return HttpResponseRedirect('/dashboard/')
        else:
            form = LoginForm()
        return render(request,'login.html',{'form':form})
    else:
        return HttpResponseRedirect('/dashboard/')
    
# Add_Blog

def add_blog(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = BlogForm(request.POST)
            if form.is_valid():
                title = form.cleaned_data['title']
                content = form.cleaned_data['content']
                blg = BlogModel(title=title, content=content)
                blg.save()
                form = BlogForm()
                #or form.save()
        else:
            form = BlogForm()
        return render(request, 'addblog.html',{'form':form})
    else:
        return HttpResponseRedirect('/login/')
    
# Update_Blog

def update_blog(request, id):
    if request.user.is_authenticated:
        if request.method == 'POST':
            blg = BlogModel.objects.get(pk=id)
            form = BlogForm(request.POST, instance=blg)
            if form.is_valid():
                form.save()
        else:
            blg = BlogModel.objects.get(pk=id)
            form = BlogForm(instance=blg)
        return render(request, 'updateblog.html',{'form':form})
    else:
        return HttpResponseRedirect('/login/')
    
# Delete_Blog

def delete_blog(request, id):
    if request.user.is_authenticated:
        if request.method == 'POST':
            blg = BlogModel.objects.get(pk=id)
            blg.delete()
        return HttpResponseRedirect('/dashboard/')
    else:
        return HttpResponseRedirect('/login/')

templates/about.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="col-sm-10">
    <h3 class="text-white my-5">About Page</h3>

    <div class="container">
        
        <p class="lead">Hi this is Kuldeep Sharma. Great web developer</p>
        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Officia deserunt libero ipsum eius, modi at quae placeat facere, recusandae ullam quasi minus corrupti vitae? Doloribus totam a tenetur aut laboriosam animi, ipsam iure maxime! Sunt id autem architecto quo ut rerum placeat, non dolore possimus maiores quibusdam, earum nam ipsa.</p>
    </div>
    
</div>

{% endblock content %}

templates/addblog.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5"> Dashboard/ Add Blog</h3>
    <form action="" method="post">
    {% csrf_token%}
        {{form.as_p}} 
        <input type="submit" value="Add" class="btn btn-success">
        <a href="{% url 'dashboard' %}" class="btn btn-danger"> Cancel </a>   
    </form>
</div>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <title>Document</title>
   
</head>
<body>
    <div class="container-fluid bg-dark">
        {% include 'navbar.html' %}
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                {% block msg %}
                {% endblock msg%}
            </div>
        </div>
        <div class="row">
            {% block side %}
            {% endblock side %}
            
            {% block content %}
            {% endblock content %}
        </div> 
    </div>

<script src="{% static 'js/bootstrap.js' %}"></script> 
</body>
</html>

templates/dashboard.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="col-sm-10">
    <h3 class="text-white my-5">Dashboard Page</h3>
    <a href="{% url "addblog" %}" class="btn btn-success">Add Post</a>
    <h4 class="text-center alert alert-info mt-3">Show Blog Information</h4>
    {% if blog %}
    <table class="tabel bg-dark ">
        <thead>
            <tr class="text-center">
                <th scope="col" style="width: 2%"> ID </th>
                <th scope="col" style="width: 2%"> Title </th>
                <th scope="col" style="width: 5%"> Content </th>
                <th scope="col" style="width: 5%"> Publication Date </th>
                <th scope="col" style="width: 5%"> Action </th>
            </tr>
        </thead>
        <tbody>
            {% for blogs in blog %}
            <tr>
                <th class="text-center">{{blogs.id}}</th>
                <td>{{blogs.title}}</td>
                <td>{{blogs.content}}</td>
                <td class="text-center">{{blogs.publication_date}}</td>
                <td class="text-center">
                    <a href="{% url "updateblog" blogs.id%}" class="btn btn-warning btn-sm">Edit</a>
                    {% if perms.myapp.delete_blogmodel %}
                    <form action="{% url "deleteblog" blogs.id %}" method='post' class="d-inline">
                    {% csrf_token %}
                        <input type="submit" class="btn btn-danger btn-sm" value="Delete">
                    </form>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <h4 class="text-center alert alert-warning">No Records</h4>
    {% endif %}
</div>
{% endblock content %}

templates/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="col-sm-10">
    <h3 class="text-white my-5">Home Page</h3>
    {% for blogs in blog%}
        <div class="container">
            <h1 class="display-4">{{blogs.title}}</h1>
            <p class="lead">{{blogs.content}}</p>
            <footer>{{blogs.publication_date}}</footer>
        </div>
    {% endfor %}
</div>

{% endblock content %}

templates/login.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="col-sm-10" >
    <h3 class="text-white my-5">Login Page</h3>
    <form action="" method="post" >
        {% csrf_token %}
        {% for fm in form  %}
            <div class="form-group">
            {{fm.label_tag}} {{fm}} {{fm.errors|striptags}}
            </div>
        {% endfor %}
        <br>
        <input type="submit" class="btn btn-primary" value="Login">
        {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
                <p>{{error}}</p>
            {% endfor %}
        {% endif %}

    </form>
</div>  

{% endblock content %}

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
    <div class="container-fluid">
      <a class="navbar-brand">Mini Blog</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "about" %}">About</a>
          </li>
       
          <li class="nav-item">
            <a class="nav-link" href="{% url "dashboard" %}">Dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "logout" %}">Logout</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "signup" %}">Signup</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "login" %}">Login</a>
          </li>
       
        </ul>
      </div>
    </div>
  </nav>

templates/signup.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="col-sm-10">
    <h3 class="text-white my-5">Signup Page</h3>
    <form action="" method="post" novalidate>
    {% csrf_token %}
    {% for fm in form%}
        <div class="form-group">
        {{fm.label_tag}} {{fm}} {{fm.errors|striptags}}
        </div>
    {% endfor %}
    <br>
    <input type="submit" value="Signup" class="btn btn-primary">
    
    {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
            <p class="alert alert-danger my-3">{{error}}</p>
            {% comment %} <p>{{error}}</p> {% endcomment %}
        {% endfor %}
    {% endif %}

    </form>
</div>
{% endblock content %}

templates/updateblog.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5"> Dashboard/ Update Blog</h3>
    <form action="" method="post">
    {% csrf_token%}
        {{form.as_p}} 
        <input type="submit" value="Update" class="btn btn-success">
        <a href="{% url 'dashboard' %}" class="btn btn-danger"> Cancel </a>   
    </form>
</div>
{% endblock content %}